config/routes.rb
Rails.application.routes.draw do

  get 'order_item/create'

  get 'order_item/update'

  get 'order_item/destroy'

  get 'customer/new'

  get 'customer/create'

  get 'order/new'

  get 'order/create'

  get 'cart/index'

  get 'contact/contact'
  get 'order/show'

  # get 'about/about'
  get 'home/index'
  get '/about', to: 'about#about', as: 'about'
  get '/contact', to: 'contact#contact', as: 'contact'

  root to: 'home#index'

  resources :categories, only:[:show]
  # root to: 'home#index'
  # root to: 'categories#home/index'

  resources :products, only: [:index, :show] do
    collection do
      post :clear_cart
    end
    member do
      post :add_to_cart # POST /products/:id/add_to_cart
      post :remove_from_cart  # POST /products/:id/remove_from_cart
    end
  end

  resources :cart, only: [:index] do
    collection do
      post :reload_quantity
      post :delete_item
    end
  end

  resources :order do
    collection do
      post :create_order
    end
  end

  root to: 'products#index'

  devise_for :customers, :controllers => { registrations: "customers/registrations"}
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/about.rb
class About < ApplicationRecord
  validates :description, presence: true
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
  validates :name, presence: true
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :description, presence: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  devise :database_authenticatable, :registerable, :recoverable, :trackable, :validatable

  validates :first_name, :last_name, :email, :street, :number, :zipcode, :province_id, :city, presence: true
  validates :first_name, :last_name, length: {minimum: 2}
  validates :email, uniqueness: true
  # found at: https://stackoverflow.com/questions/19353135/what-is-good-way-to-validates-canadian-postal-code-in-rails
  # canadian_postal_code = /[ABCEGHJKLMNPRSTVXY]{1}\d{1}[A-Z]{1}[ -]?\d{1}[A-Z]{1}\d{1}/
  # validates :postal_code, format: { with: canadian_postal_code }
  has_many :orders
  belongs_to :province
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  belongs_to :status
  has_many :order_items
  has_many :products, through: :order_items

  before_create :set_status
  before_save :set_subtotal

  def pst
    (subtotal * customer.province.pst)
  end

  def gst
    (subtotal * customer.province.gst)
  end

  def hst
    (subtotal * customer.province.hst)
  end

  def subtotal
    order_items.collect { |oi| oi.valid? ? (oi.quantity * oi.price) : 0 }.sum
  end

  def total
    subtotal + pst + gst + hst
  end

  private
  def set_subtotal
    self[:subtotal] = subtotal
  end

  def set_gst
    self[:gst] = pst
  end

  def set_pst
    self[:pst] = pst
  end

  def set_hst
    self[:hst] = hst
  end

  def set_total
    self[:total] = total
  end

  def set_status
    self.status_id = 1
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product
  before_save :set_unit_price

  def price
    if persisted?
      self[:price]
    else
      product.price
    end
  end

  # def quantity
  #   # session[:add_to_cart]['quantity']
  # end

  private
  # def product_present
  #   if product.nil?
  #     errors.add(:product, "is not valid or is not active.")
  #   end
  # end
  #
  # def order_present
  #   if order.nil?
  #     errors.add(:order, "is not a valid order.")
  #   end
  # end

  def set_unit_price
    self[:price] = price
  end
end

app/models/payment_method.rb
class PaymentMethod < ApplicationRecord
  validates :name, presence: true
end

app/models/product.rb
class Product < ApplicationRecord

  # Paperclip
  has_attached_file :image,
                    :styles => {
                        :thumb => ["40x40%", :jpg],
                        :small  => ["120x120%",:jpg],
                        :medium => ["200x200%",:jpg] }


  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  validates :name, :description, :stock_quantity, :price, :category, presence: true
  validates :stock_quantity, numericality: { only_integer: true }
  validates :price, numericality: true

  belongs_to :category
  has_many :order_items
  has_many :orders, through: :order_items

  def image_attributes=(attributes)
    # Marks the attachment for destruction on next save,
    # if the attributes hash contains a _destroy flag
    # and a new avatar was not uploaded at the same time:
    image.clear if has_destroy_flag?(attributes) && !image.dirty?
  end

  def self.search(category_id)
    if category_id != ''
      where('categories_id = ?', category_id).joins(:category)
    end
  end

end

app/models/province.rb
class Province < ApplicationRecord
  has_many :customers
  # validates :name, :code, presence: true
end

app/models/status.rb
class Status < ApplicationRecord
  has_many :orders
  validates :name, presence: true
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/customer_helper.rb
module CustomerHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/order_item_helper.rb
module OrderItemHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/shared/_error_alert.html.erb
<div class="alert alert-dismissible alert-warning">
  <%= @error_alert %>
  <button type="button" class="close" data-dismiss="alert">&times;</button>
</div>

app/views/layouts/shared/_header.html.erb
<header>
  <h1 class="title">Prairie Brazil Store</h1>
</header>
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="collapse navbar-collapse" id="navbarColor01">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link active" href="/">Home</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link active" href="/about">About Us</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="/contact">Contact</a>
      </li>
      <% if customer_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Logout", destroy_customer_session_path, method: :delete, class: "nav-link active"  %>
        </li>
        <li class="nav-item active">
          <div class = "nav-link active">Signed in as: <%= current_customer.first_name %></div>
        </li>
      <% else %>
        <li class="nav-item active">
          <%= link_to "Sign Up", new_customer_registration_path, class: "nav-link active" %>
        </li>
        <li class="nav-item active">
          <%= link_to "Login", new_customer_session_path, class: "nav-link active" %>
        </li>
      <% end %>

    </ul>
    <ul class="navbar-nav">
      <li class="nav-item cart">
        <a class="btn btn-default" href="/cart/index"><%= icon('fas', 'shopping-cart') %></a>
      </li>
      <li class="nav-item">
        <% if session[:add_to_cart] != nil %>
          <h5 class="prod number_of_prods"><%= pluralize session[:add_to_cart].count, 'Product' %></h5>
        <% else %>
          <h5 class="prod number_of_prods">0 Products</h5>
        <% end %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/shared/_menu.html.erb
<!--<ul class="list-group ">-->
  <!--<a href="#" class="list-group-item list-group-item-action active">-->
    <!--Categories-->
  <!--</a>-->

  <!--<li class="list-group-item d-flex justify-content-between align-items-center">-->
    <!--Morbi leo risus-->
  <!--</li>-->
  <!--<li class="list-group-item d-flex justify-content-between align-items-center">-->
    <!--Cras justo odio-->
  <!--</li>-->
  <!--<li class="list-group-item d-flex justify-content-between align-items-center">-->
    <!--Dapibus ac facilisis in-->
  <!--</li>-->
  <!--<li class="list-group-item d-flex justify-content-between align-items-center">-->
    <!--Morbi leo risus-->
  <!--</li>-->
<!--</ul>-->

app/views/layouts/shared/_success_alert.html.erb
<div class="alert alert-dismissible alert-success">
  <%= @success_alert %>
  <button type="button" class="close" data-dismiss="alert">&times;</button>
</div>