config/routes.rb
Rails.application.routes.draw do

  get 'order_item/create'

  get 'order_item/update'

  get 'order_item/destroy'

  get 'customer/new'

  get 'customer/create'

  get 'order/new'

  get 'order/create'

  get 'cart/index'

  get 'contact/contact'
  get 'order/show'

  # get 'about/about'
  get 'home/index'
  get '/about', to: 'about#about', as: 'about'
  get '/contact', to: 'contact#contact', as: 'contact'

  root to: 'home#index'

  resources :categories, only:[:show]
  # root to: 'home#index'
  # root to: 'categories#home/index'

  resources :products, only: [:index, :show] do
    collection do
      post :clear_cart
    end
    member do
      post :add_to_cart # POST /products/:id/add_to_cart
      post :remove_from_cart  # POST /products/:id/remove_from_cart
    end
  end

  resources :cart, only: [:index] do
    collection do
      post :reload_quantity
      post :delete_item
    end
  end

  resources :order do
    collection do
      post :create_order
    end
  end

  root to: 'products#index'

  devise_for :customers, :controllers => { registrations: "customers/registrations"}
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/about.rb
class About < ApplicationRecord
  validates :description, presence: true
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
  validates :name, presence: true
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :description, presence: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  devise :database_authenticatable, :registerable, :recoverable, :trackable, :validatable

  validates :first_name, :last_name, :email, :street, :number, :zipcode, :province_id, :city, presence: true
  validates :first_name, :last_name, length: {minimum: 2}
  validates :email, uniqueness: true
  # found at: https://stackoverflow.com/questions/19353135/what-is-good-way-to-validates-canadian-postal-code-in-rails
  # canadian_postal_code = /[ABCEGHJKLMNPRSTVXY]{1}\d{1}[A-Z]{1}[ -]?\d{1}[A-Z]{1}\d{1}/
  # validates :postal_code, format: { with: canadian_postal_code }
  has_many :orders
  belongs_to :province
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  belongs_to :status
  has_many :order_items
  has_many :products, through: :order_items

  before_create :set_status
  before_save :set_subtotal

  def pst
    (subtotal * customer.province.pst)
  end

  def gst
    (subtotal * customer.province.gst)
  end

  def hst
    (subtotal * customer.province.hst)
  end

  def subtotal
    order_items.collect { |oi| oi.valid? ? (oi.quantity * oi.price) : 0 }.sum
  end

  def total
    subtotal + pst + gst + hst
  end

  private
  def set_subtotal
    self[:subtotal] = subtotal
  end

  def set_gst
    self[:gst] = pst
  end

  def set_pst
    self[:pst] = pst
  end

  def set_hst
    self[:hst] = hst
  end

  def set_total
    self[:total] = total
  end

  def set_status
    self.status_id = 1
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product
  before_save :set_unit_price

  def price
    if persisted?
      self[:price]
    else
      product.price
    end
  end

  # def quantity
  #   # session[:add_to_cart]['quantity']
  # end

  private
  # def product_present
  #   if product.nil?
  #     errors.add(:product, "is not valid or is not active.")
  #   end
  # end
  #
  # def order_present
  #   if order.nil?
  #     errors.add(:order, "is not a valid order.")
  #   end
  # end

  def set_unit_price
    self[:price] = price
  end
end

app/models/payment_method.rb
class PaymentMethod < ApplicationRecord
  validates :name, presence: true
end

app/models/product.rb
class Product < ApplicationRecord

  # Paperclip
  has_attached_file :image,
                    :styles => {
                        :thumb => ["40x40%", :jpg],
                        :small  => ["120x120%",:jpg],
                        :medium => ["200x200%",:jpg] }


  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  validates :name, :description, :stock_quantity, :price, :category, presence: true
  validates :stock_quantity, numericality: { only_integer: true }
  validates :price, numericality: true

  belongs_to :category
  has_many :order_items
  has_many :orders, through: :order_items

  def image_attributes=(attributes)
    # Marks the attachment for destruction on next save,
    # if the attributes hash contains a _destroy flag
    # and a new avatar was not uploaded at the same time:
    image.clear if has_destroy_flag?(attributes) && !image.dirty?
  end

  def self.search(category_id)
    if category_id != ''
      where('categories_id = ?', category_id).joins(:category)
    end
  end

end

app/models/province.rb
class Province < ApplicationRecord
  has_many :customers
  # validates :name, :code, presence: true
end

app/models/status.rb
class Status < ApplicationRecord
  has_many :orders
  validates :name, presence: true
end

app/controllers/order_controller.rb
class OrderController < ApplicationController

  before_action :authenticate_customer!

  def new
    # get customer information
    @customer = Customer.find(current_customer.id)
    @province = Province.find(@customer.province_id)

    @full_name = @customer.first_name + " " + @customer.last_name
    if !@customer.suit_number == nil
      @address = @customer.suit_number + " " + @customer.number + " - " + @customer.street
    else
      @address = @customer.number + " - " + @customer.street
    end

    # get products
    @final_produts = session[:add_to_cart]

    # calculate order amount
    @subtotal = session[:subtotal]

    if !@province.hst == nil
      @tax_rate = @province.hst
    else
      @tax_rate = @province.gst + @province.pst
    end

    @taxes = @subtotal.to_f * @tax_rate
    @total = @subtotal.to_f + @taxes
  end

  def create_order

    @customer = Customer.find(current_customer.id)
    @province = Province.find(@customer.province_id)

    @subtotal = session[:subtotal].to_f
    @total = @subtotal

    @order = Order.new
    if @province.pst != nil
      @order.pst = @subtotal * @province.pst
      @total += @subtotal * @province.pst
    end
    if @province.hst != nil
      @order.hst = @subtotal * @province.hst
      @total += @subtotal * @province.hst
    end
    if @province.gst != nil
      @order.gst = @subtotal * @province.gst
      @total += @subtotal * @province.gst
    end
    @order.subtotal = @subtotal.to_f
    @order.customer_id = @customer.id
    @order.status_id = 1
    @order.total = @total
    @order.save!

    @orderItems = []
    @array_prods = session[:add_to_cart]

    @array_prods.each do |p|
      # pid =  p["id"].keys[0].to_i
      @oi = OrderItem.new
      @oi.product_id = p["id"]
      @oi.price=p["price"]
      @oi.quantity=p["quantity"]
      @orderItems << @oi
    end
    @order.order_items = @orderItems
    @order.save!

  end

end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/customer_helper.rb
module CustomerHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/order_item_helper.rb
module OrderItemHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/order/create.html.erb
<h1>Order#create</h1>
<p>Find me in app/views/order/create.html.erb</p>

app/views/order/new.html.erb
<% if !customer_signed_in? %>
 <p>Please, log in.</p>
<% else %>
  <div class="container">
    <p><h1>My information</h1></br></p>
    <div class="row">
      <div class="col-lg-9">
        <div class="panel panel-default">
          <div class="panel-body">

            <label for="firstname">Name: </label>
            <label for="firstname"><%= @full_name %></label></br>

            <label for="address">Address: </label>
            <label for="address"><%= @address %></label></br>

            <label for="city">City: </label>
            <label for="city"><%= @customer.city %></label></br>

            <label for="province">Province: </label>
            <label for="Province"><%= @customer.province.name %></label>
          </div>
        </div>

        <p><h1>My Order</h1></br></p>
        <div class="row">
          <div class="col-lg-9">
            <% @final_produts.each do |fp| %>
              <div class="panel panel-default">
                <div class="panel-body">
                  <label for="product_name">Product Name: </label>
                  <label for="subtotal"><%= fp["name"] %></label></br>
                  <label for="product_quantity">Quantity: </label>
                  <label for="product_quantity"><%= fp["quantity"] %></label></br>
                  <label for="product_total">Amount: </label>
                  <label for="product_total"><%= number_to_currency fp["total"] %></label></br>
                </div>
              </div>
            <% end %>
            <div class="panel panel-default">
              <div class="panel-body">

              <label for="subtotal"><strong>Subtotal: </strong></label>
              <label for="subtotal"><strong><%= number_to_currency @subtotal %></strong></label></br>

              <label for="taxes"><strong>Taxes: </strong></label>
              <label for="taxes"><strong><%= number_to_currency @taxes %></strong></label></br>

              <label for="total"><strong>Total: </strong></label>
              <label for="total"><strong><%= number_to_currency @total %></strong></label></br>

          </div>
        </div>
      </div>
      </div>
        <div class="cart_item">
          <%= link_to "Proceed to Checkout", create_order_order_index_path, class: 'btn btn-primary', method: :post %>

        </div>
      </div>
    </div>
  </div>
<% end %>